package com.empyra.utils;

public enum Role {
	SYSTEM_ADMINISTRATOR,
	PROPERTY_MANAGER,
	PMO_SUPERVISOR,
	PMO_CLERK,
	MAINTENANCE_COORDINATOR,
	MAINTENANCE_STAFF,
	SECURITY_HEAD,
	ROVING_GUARD,
	GATE_GUARD,
	UNIT_OWNER,
	TENANT,
	HOUSEHOLD_MEMBER
}
