-- Database: EMPYRA

-- DROP DATABASE IF EXISTS "EMPYRA";

CREATE DATABASE "EMPYRA"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_Philippines.1252'
    LC_CTYPE = 'English_Philippines.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE TABLE USERS (
	USER_ID varchar(20),
	FIRST_NAME varchar(225),
	MIDDLE_NAME varchar(225),
	LAST_NAME varchar(225),
	USER_ROLE varchar (20),
	CONTACT_NUMBER varchar (225),
	STATUS varchar (20),
	CREATED_AT date,
	CREATED_BY varchar (20),
	DEPARTMENT varchar (50)
	
);


--FIRST USERS
--System Administration
INSERT INTO USERS (
  USER_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, USER_ROLE,
  CONTACT_NUMBER, STATUS, CREATED_AT, CREATED_BY, DEPARTMENT
) VALUES (
  'EMPYRA-SYS-00001', 'ESSINAYA', 'CAELUMRISCH', 'DE BOREL', 'SYSTEM_ADMIN',
  '09170000001', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'SYSTEM_ADMINISTRATION'
);


--Property Management Office
INSERT INTO USERS (
  USER_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, USER_ROLE,
  CONTACT_NUMBER, STATUS, CREATED_AT, CREATED_BY, DEPARTMENT
) VALUES
(
  'EMPYRA-PMO-00001', 'ÉTIENNE', 'LAURENT', 'DE FORTEMPS', 'PMO_CLERK',
  '09170000011', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'PROPERTY_MANAGEMENT'
),
(
  'EMPYRA-PMO-00002', 'YSABEAU', 'CLÉMENCE', 'DE GORGAGNE', 'PMO_SUPERVISOR',
  '09170000012', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'PROPERTY_MANAGEMENT'
),
(
  'EMPYRA-PMO-00003', 'THIBAULT', 'RENÉ', 'CORNEVAL', 'PROPERTY_MANAGER',
  '09170000013', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'PROPERTY_MANAGEMENT'
);



--Security
INSERT INTO USERS (
  USER_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, USER_ROLE,
  CONTACT_NUMBER, STATUS, CREATED_AT, CREATED_BY, DEPARTMENT
) VALUES
(
  'EMPYRA-SEC-00001', 'BASTIEN', 'OLIVIER', 'DZEMAEL', 'SECURITY_HEAD',
  '09170000021', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'SECURITY'
),
(
  'EMPYRA-SEC-00002', 'ARNAUT', 'GUILLAUME', 'DE CHEVALLIER', 'GATE_GUARD',
  '09170000022', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'SECURITY'
),
(
  'EMPYRA-SEC-00003', 'RENAUD', 'MARC', 'CORNEVAL', 'ROVING_GUARD',
  '09170000023', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'SECURITY'
);




--Maintenance
INSERT INTO USERS (
  USER_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, USER_ROLE,
  CONTACT_NUMBER, STATUS, CREATED_AT, CREATED_BY, DEPARTMENT
) VALUES
(
  'EMPYRA-MNT-00001', 'MARCEL', 'ÉTIENNEL', 'ROCHEFAUX', 'MAINTENANCE_COORDINATOR',
  '09170000031', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'MAINTENANCE'
),
(
  'EMPYRA-MNT-00002', 'ODON', 'PASCAL', 'FERRAULT', 'MAINTENANCE_STAFF',
  '09170000032', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'MAINTENANCE'
);



--Residents
INSERT INTO USERS (
  USER_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, USER_ROLE,
  CONTACT_NUMBER, STATUS, CREATED_AT, CREATED_BY, DEPARTMENT
) VALUES
(
  'EMPYRA-RES-00001', 'CÉLESTE', 'MARIELLE', 'DE LAMITTE', 'UNIT_OWNER',
  '09170000041', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'RESIDENT_SERVICES'
),
(
  'EMPYRA-RES-00002', 'ADRIEN', 'LUCIEN', 'MONTFAUCON', 'TENANT',
  '09170000042', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'RESIDENT_SERVICES'
),
(
  'EMPYRA-RES-00003', 'MAËLYS', 'ÉLODIE', 'D’AUBRAC', 'HOUSEHOLD_MEMBER',
  '09170000043', 'ACTIVE', CURRENT_DATE, 'SYSTEM', 'RESIDENT_SERVICES'
);

